# Generated by Django 5.1 on 2024-09-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0003_alter_blogpost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='date',
            new_name='post_date',
        ),
    ]
