# Generated by Django 5.1 on 2024-09-05 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0004_rename_date_blogpost_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
