# Generated by Django 5.1 on 2024-09-05 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0005_remove_blogpost_post_date_blogpost_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
