# Generated by Django 5.1 on 2024-09-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0007_alter_blogpost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
